let questions = [
                    [
                        1,
                        "Do you walk faster",
                        "I'm faster",
                        "I'm slower",
                        "walk faster",
                        "walk slower",
                        844,
                        584,
                        257
                    ],
                    [
                        2,
                        "Do you eat healthier food",
                        "I'm healthier",
                        "I'm less healthily",
                        "eat healthier",
                        "eat less healthily",
                        841,
                        343,
                        498
                    ],
                    [
                        3,
                        "Do you care more about the environment",
                        "I care more",
                        "I care less",
                        "care more about the environment",
                        "care less about the environment",
                        841,
                        603,
                        238
                    ],
                    [
                        4,
                        "Are you better at keeping your home tidy",
                        "I'm better",
                        "I'm worse",
                        "are better at keeping their home tidy",
                        "are worse at keeping their home tidy",
                        841,
                        233,
                        608
                    ],
                    [
                        5,
                        "Are you smarter",
                        "I'm smarter",
                        "I'm less smart ",
                        "are smarter",
                        "are less smart",
                        842,
                        733,
                        108
                    ],
                    [
                        6,
                        "Are your feet look better",
                        "they're better",
                        "they're worse",
                        "have better looking feet",
                        "have worse looking feet",
                        841,
                        297,
                        544
                    ],
                    [
                        7,
                        "Are you a better listener",
                        "I'm better",
                        "I'm worse",
                        "are a better listener",
                        "are a worse listener",
                        841,
                        490,
                        351
                    ],
                    [
                        8,
                        "Are you more privileged",
                        "I'm more",
                        "I'm less",
                        "are more privileged",
                        "are less privileged",
                        841,
                        695,
                        146
                    ],
                    [
                        9,
                        "Do you smell better",
                        "I smell better",
                        "I smell worse",
                        "smell better",
                        "smell worse",
                        841,
                        382,
                        459
                    ],
                    [
                        10,
                        "Are you a better communicator",
                        "I'm better",
                        "I'm worse",
                        "are a better communicator",
                        "are a worse communicator",
                        842,
                        362,
                        480
                    ],
                    [
                        11,
                        "Are you better at washing up dishes",
                        "I'm better",
                        "I'm worse",
                        "are better at washing up",
                        "are worse at washing up",
                        839,
                        327,
                        513
                    ],
                    [
                        12,
                        "Are you more curious",
                        "I'm more",
                        "I'm less",
                        "are more curious",
                        "are less curious",
                        841,
                        692,
                        149
                    ],
                    [
                        13,
                        "Are you happier",
                        "I'm happier",
                        "I'm less happy",
                        "are happier",
                        "are less happy",
                        841,
                        327,
                        514
                    ],
                    [
                        14,
                        "Are you kinder",
                        "I'm kinder",
                        "I'm less kind",
                        "are kinder",
                        "are less kind",
                        841,
                        606,
                        235
                    ],
                    [
                        15,
                        "Do you have better ideas",
                        "they're better",
                        "they're worse",
                        "have better ideas",
                        "have worse ideas",
                        841,
                        510,
                        331
                    ],
                    [
                        16,
                        "Are you more conservative",
                        "I'm more",
                        "I'm less",
                        "are more conservative",
                        "are less conservative",
                        841,
                        119,
                        722
                    ],
                    [
                        17,
                        "Do you complain more",
                        "I complain more",
                        "I complain less",
                        "complain more",
                        "complain less",
                        841,
                        422,
                        419
                    ],
                    [
                        18,
                        "Do you give more to homeless  people",
                        "I give more",
                        "I give less",
                        "give more to homeless people",
                        "give less to homeless people",
                        842,
                        173,
                        668
                    ],
                    [
                        19,
                        "Do you have a better music taste",
                        "It's better",
                        "It's worse",
                        "have a better music taste",
                        "have a worse music taste",
                        841,
                        501,
                        340
                    ],
                    [
                        20,
                        "Do you give better gifts",
                        "they're better",
                        "they're worse",
                        "give better gifts",
                        "give worse gifts",
                        841,
                        305,
                        536
                    ],
                    [
                        21,
                        "Are you a better friend",
                        "I'm better",
                        "I'm worse",
                        "are a better friend",
                        "are a worse friend",
                        841,
                        387,
                        454
                    ],
                    [
                        22,
                        "Are you more progressive",
                        "I'm more",
                        "I'm less",
                        "are more progressive",
                        "are less progressive",
                        841,
                        680,
                        161
                    ],
                    [
                        23,
                        "Are you better looking",
                        "I'm better",
                        "I'm worse",
                        "are better looking",
                        "are worse looking",
                        842,
                        348,
                        493
                    ],
                    [
                        24,
                        "Are you more interesting",
                        "I'm more",
                        "I'm less",
                        "are more interesting",
                        "are less interesting",
                        775,
                        378,
                        398
                    ],
                    [
                        25,
                        "Are you better at your work",
                        "I'm better",
                        "I'm worse",
                        "are better at their work",
                        "are worse at their work",
                        774,
                        452,
                        322
                    ],
                    [
                        26,
                        "Are you more ambitious",
                        "I'm more",
                        "I'm less",
                        "are more ambitious",
                        "are less ambitious",
                        769,
                        310,
                        460
                    ],
                    [
                        27,
                        "Are you more creative",
                        "I'm more",
                        "I'm less",
                        "are more creative",
                        "are less creative",
                        727,
                        379,
                        348
                    ],
                    [
                        28,
                        "Are you better at sex",
                        "I'm better",
                        "I'm worse",
                        "are better at sex",
                        "are worse at sex",
                        199,
                        63,
                        136
                    ],
                    [
                        29,
                        "Are you more patient",
                        "I'm more",
                        "I'm less",
                        "are more patient",
                        "are less patient",
                        727,
                        422,
                        305
                    ],
                    [
                        30,
                        "Do you have better dental hygiene",
                        "better",
                        "worse",
                        "have better dental hygiene",
                        "have worse dental hygiene",
                        227,
                        93,
                        134
                    ],
                    [
                        31,
                        "Do you procrastinate more",
                        "more",
                        "less",
                        "procrastinate more",
                        "procrastinate less",
                        227,
                        193,
                        34
                    ],
                    [
                        32,
                        "Are you a better driver",
                        "I'm better",
                        "I'm worse",
                        "are a better driver",
                        "are a worse driver",
                        227,
                        95,
                        133
                    ],
                    [
                        33,
                        "Did you have a better childhood",
                        "it was better",
                        "it was worse",
                        "had a better childhood",
                        "had a worse childhood",
                        226,
                        156,
                        71
                    ],
                    [
                        34,
                        "Are you a better hugger",
                        "I'm better",
                        "I'm worse",
                        "are a better hugger",
                        "are a worse hugger",
                        224,
                        102,
                        122
                    ],
                    [
                        35,
                        "Are you funnier",
                        "I'm funnier",
                        "I'm less funny",
                        "are funnier",
                        "are less funny",
                        224,
                        128,
                        96
                    ],
                    [
                        36,
                        "Are you better at maths",
                        "I'm better",
                        "I'm worse",
                        "are better at maths",
                        "are worse at maths",
                        224,
                        148,
                        76
                    ],
                    [
                        37,
                        "Do you spend more time on your phone",
                        "more",
                        "less",
                        "spend more time on their phone",
                        "spend less time on their phone",
                        222,
                        135,
                        88
                    ],
                    [
                        38,
                        "Are you more narcissistic",
                        "I'm more",
                        "I'm less",
                        "are more narcissistic",
                        "are less narcissistic",
                        221,
                        82,
                        139
                    ],
                    [
                        39,
                        "Are you more stereotypically your gender",
                        "I'm more",
                        "I'm less",
                        "are more stereotypically their gender",
                        "are less stereotypically their gender",
                        216,
                        44,
                        172
                    ],
                    [
                        40,
                        "Do you have a better memory",
                        "it's better",
                        "it's worse",
                        "have a better memory",
                        "have a worse memory",
                        216,
                        80,
                        136
                    ],
                    [
                        41,
                        "Are you more humble",
                        "I'm more",
                        "I'm less",
                        "are more humble",
                        "are less humble",
                        209,
                        109,
                        100
                    ],
                    [
                        42,
                        "Are you better at cooking",
                        "I'm better",
                        "I'm worse",
                        "are better at cooking",
                        "are worse at cooking",
                        117,
                        51,
                        66
                    ],
                    [
                        43,
                        "Do you change your bed sheets more",
                        "more",
                        "less",
                        "change their bed sheets more",
                        "change their bed sheets less",
                        103,
                        14,
                        89
                    ],
                    [
                        44,
                        "Do you have more common sense",
                        "I have more",
                        "I have less",
                        "have more common sense",
                        "have less common sense",
                        77,
                        57,
                        20
                    ],
                    [
                        45,
                        "Are more confident ",
                        "I'm more",
                        "I'm less",
                        "are more confident",
                        "are less confident",
                        72,
                        25,
                        47
                    ],
                    [
                        46,
                        "Do you exercise more",
                        "more",
                        "less",
                        "exercise more",
                        "exercise less",
                        5,
                        2,
                        3
                    ],
                    [
                        47,
                        "Do you read more",
                        "more",
                        "less",
                        "read more",
                        "read less",
                        5,
                        1,
                        4
                    ],
                    [
                        48,
                        "Do you sleep more ",
                        "more",
                        "less",
                        "sleep more",
                        "sleep less",
                        5,
                        3,
                        2
                    ],
                    [
                        49,
                        "Do you have more friends ",
                        "I have more",
                        "I have less",
                        "have more friends",
                        "have less friends",
                        5,
                        3,
                        2
                    ],
                    [
                        50,
                        "Are you healthier",
                        "I'm healthier",
                        "I'm less healthy",
                        "are healthier",
                        "are less healthy",
                        5,
                        3,
                        2
                    ],
                    [
                        51,
                        "Are you more religious",
                        "I'm more",
                        "I'm less",
                        "are more religious",
                        "are less religious",
                        5,
                        0,
                        5
                    ],
                    [
                        52,
                        "Are you more optimistic",
                        "I'm more",
                        "I'm less",
                        "are more optimistic",
                        "are less optimistic",
                        5,
                        3,
                        2
                    ]
]
        
    

    