let questions = [
        {
            "Number": 1,
            "Question": "Do you walk faster",
            "Pro": "I'm faster",
            "Neg": "I'm slower",
            "Positve response": "walk faster",
            "Negative Response": "walk slower",
            "Total": 1681,
            "Yes": 1167,
            "No": 514
        },
        {
            "Number": 2,
            "Question": "Do you eat healthier food",
            "Pro": "I'm healthier",
            "Neg": "I'm less healthily",
            "Positve response": "eat healthier",
            "Negative Response": "eat less healthily",
            "Total": 1681,
            "Yes": 686,
            "No": 995
        },
        {
            "Number": 3,
            "Question": "Do you care more about the environment",
            "Pro": "I care more",
            "Neg": "I care less",
            "Positve response": "care more about the enviroment",
            "Negative Response": "care less about the enviroment",
            "Total": 1681,
            "Yes": 1205,
            "No": 476
        },
        {
            "Number": 4,
            "Question": "Are you better at keeping your home tidy",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are better at keeping their home tidy",
            "Negative Response": "are worse at keeping their home tidy",
            "Total": 1681,
            "Yes": 465,
            "No": 1216
        },
        {
            "Number": 5,
            "Question": "Are you smarter",
            "Pro": "I'm smarter",
            "Neg": "I'm less smart ",
            "Positve response": "are smarter",
            "Negative Response": "are less smart",
            "Total": 1681,
            "Yes": 1466,
            "No": 215
        },
        {
            "Number": 6,
            "Question": "Are your feet look better",
            "Pro": "they're better",
            "Neg": "they're worse",
            "Positve response": "have better looking feet",
            "Negative Response": "have worse looking feet",
            "Total": 1681,
            "Yes": 593,
            "No": 1088
        },
        {
            "Number": 7,
            "Question": "Are you a better listener",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are a better listener",
            "Negative Response": "are a worse listener",
            "Total": 1681,
            "Yes": 979,
            "No": 702
        },
        {
            "Number": 8,
            "Question": "Are you more privileged",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more privileged",
            "Negative Response": "are less privileged",
            "Total": 1681,
            "Yes": 1389,
            "No": 292
        },
        {
            "Number": 9,
            "Question": "Do you smell better",
            "Pro": "I smell better",
            "Neg": "I smell worse",
            "Positve response": "smell better",
            "Negative Response": "smell worse",
            "Total": 1681,
            "Yes": 763,
            "No": 918
        },
        {
            "Number": 10,
            "Question": "Are you a better communicator",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are a better communicator",
            "Negative Response": "are a worse communicator",
            "Total": 1681,
            "Yes": 721,
            "No": 960
        },
        {
            "Number": 11,
            "Question": "Are you better at washing up dishes",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are better at washing up",
            "Negative Response": "are worse at washing up",
            "Total": 1678,
            "Yes": 653,
            "No": 1025
        },
        {
            "Number": 12,
            "Question": "Are you more curious",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more curious",
            "Negative Response": "are less curious",
            "Total": 1681,
            "Yes": 1383,
            "No": 298
        },
        {
            "Number": 13,
            "Question": "Are you happier",
            "Pro": "I'm happier",
            "Neg": "I'm less happy",
            "Positve response": "are happier",
            "Negative Response": "are less happy",
            "Total": 1681,
            "Yes": 653,
            "No": 1028
        },
        {
            "Number": 14,
            "Question": "Are you kinder",
            "Pro": "I'm kinder",
            "Neg": "I'm less kind",
            "Positve response": "are kinder",
            "Negative Response": "are less kind",
            "Total": 1681,
            "Yes": 1212,
            "No": 469
        },
        {
            "Number": 15,
            "Question": "Do you have better ideas",
            "Pro": "they're beter",
            "Neg": "they're worse",
            "Positve response": "have better ideas",
            "Negative Response": "have worse ideas",
            "Total": 1681,
            "Yes": 1019,
            "No": 662
        },
        {
            "Number": 16,
            "Question": "Are you more conservative",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more conservative",
            "Negative Response": "are less conservative",
            "Total": 1681,
            "Yes": 237,
            "No": 1444
        },
        {
            "Number": 17,
            "Question": "Do you complain more",
            "Pro": "I complain more",
            "Neg": "I complain less",
            "Positve response": "complain more",
            "Negative Response": "complain less",
            "Total": 1681,
            "Yes": 844,
            "No": 837
        },
        {
            "Number": 18,
            "Question": "Do you give more to homeless  people",
            "Pro": "I give more",
            "Neg": "I give less",
            "Positve response": "give more to homeless people",
            "Negative Response": "give less to homeless people",
            "Total": 1681,
            "Yes": 345,
            "No": 1336
        },
        {
            "Number": 19,
            "Question": "Do you have a better music taste",
            "Pro": "It's better",
            "Neg": "It's worse",
            "Positve response": "have a better music taste",
            "Negative Response": "have a worse music taste",
            "Total": 1681,
            "Yes": 1002,
            "No": 679
        },
        {
            "Number": 20,
            "Question": "Do you give better gifts",
            "Pro": "they're better",
            "Neg": "they're worse",
            "Positve response": "give better gifts",
            "Negative Response": "give worse gifts",
            "Total": 1681,
            "Yes": 610,
            "No": 1071
        },
        {
            "Number": 21,
            "Question": "Are you a better friend",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are a better friend",
            "Negative Response": "are a worse friend",
            "Total": 1681,
            "Yes": 773,
            "No": 908
        },
        {
            "Number": 22,
            "Question": "Are you more progressive",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more progressive",
            "Negative Response": "are less progressive",
            "Total": 1681,
            "Yes": 1359,
            "No": 322
        },
        {
            "Number": 23,
            "Question": "Are you better looking",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are better looking",
            "Negative Response": "are worse looking",
            "Total": 1681,
            "Yes": 696,
            "No": 985
        },
        {
            "Number": 24,
            "Question": "Are you more interesting",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more interesting",
            "Negative Response": "are less interesting",
            "Total": 1550,
            "Yes": 755,
            "No": 795
        },
        {
            "Number": 25,
            "Question": "Are you better at your work",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are better at their work",
            "Negative Response": "are worse at their work",
            "Total": 1545,
            "Yes": 903,
            "No": 642
        },
        {
            "Number": 26,
            "Question": "Are you more ambitious",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more ambitious",
            "Negative Response": "are less ambitious",
            "Total": 1538,
            "Yes": 619,
            "No": 919
        },
        {
            "Number": 27,
            "Question": "Are you more creative",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more creative",
            "Negative Response": "are less creative",
            "Total": 1453,
            "Yes": 758,
            "No": 695
        },
        {
            "Number": 28,
            "Question": "Are you better at sex",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are beter at sex",
            "Negative Response": "are worse at sex",
            "Total": 397,
            "Yes": 125,
            "No": 272
        },
        {
            "Number": 29,
            "Question": "Are you more patient",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more patient",
            "Negative Response": "are less patient",
            "Total": 1453,
            "Yes": 844,
            "No": 609
        },
        {
            "Number": 30,
            "Question": "Do you have better dental hygiene",
            "Pro": "better",
            "Neg": "worse",
            "Positve response": "have better dental hygiene",
            "Negative Response": "have worse dental hygiene",
            "Total": 454,
            "Yes": 186,
            "No": 268
        },
        {
            "Number": 31,
            "Question": "Do you procrastinate more",
            "Pro": "more",
            "Neg": "less",
            "Positve response": "procrastinate more",
            "Negative Response": "procrastinate less",
            "Total": 454,
            "Yes": 386,
            "No": 68
        },
        {
            "Number": 32,
            "Question": "Are you a better driver",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are a better driver",
            "Negative Response": "are a worse driver",
            "Total": 454,
            "Yes": 189,
            "No": 265
        },
        {
            "Number": 33,
            "Question": "Did you have a better childhood",
            "Pro": "it was better",
            "Neg": "it was worse",
            "Positve response": "had a better childhood",
            "Negative Response": "had a worse childhood",
            "Total": 452,
            "Yes": 311,
            "No": 141
        },
        {
            "Number": 34,
            "Question": "Are you a better hugger",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are a better hugger",
            "Negative Response": "are a worse hugger",
            "Total": 447,
            "Yes": 204,
            "No": 243
        },
        {
            "Number": 35,
            "Question": "Are you funnier",
            "Pro": "I'm funnier",
            "Neg": "I'm less funny",
            "Positve response": "are funnier",
            "Negative Response": "are less funny",
            "Total": 447,
            "Yes": 256,
            "No": 191
        },
        {
            "Number": 36,
            "Question": "Are you better at maths",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are better at maths",
            "Negative Response": "are worse at maths",
            "Total": 447,
            "Yes": 295,
            "No": 152
        },
        {
            "Number": 37,
            "Question": "Do you spend more time on your phone",
            "Pro": "more",
            "Neg": "less",
            "Positve response": "spend more time on their phone",
            "Negative Response": "spend less time on their phone",
            "Total": 444,
            "Yes": 269,
            "No": 175
        },
        {
            "Number": 38,
            "Question": "Are you more narcissitic",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more narcissitic",
            "Negative Response": "are less narcissitic",
            "Total": 441,
            "Yes": 164,
            "No": 277
        },
        {
            "Number": 39,
            "Question": "Are you more sterotypically your gender",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more sterotypically their gender",
            "Negative Response": "are less sterotypically their gender",
            "Total": 431,
            "Yes": 88,
            "No": 343
        },
        {
            "Number": 40,
            "Question": "Do you have a better memory",
            "Pro": "it's better",
            "Neg": "it's worse",
            "Positve response": "have a better memory",
            "Negative Response": "have a worse memory",
            "Total": 431,
            "Yes": 159,
            "No": 272
        },
        {
            "Number": 41,
            "Question": "Are you more humble",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more humble",
            "Negative Response": "are less humble",
            "Total": 416,
            "Yes": 217,
            "No": 199
        },
        {
            "Number": 42,
            "Question": "Are you better at cooking",
            "Pro": "I'm better",
            "Neg": "I'm worse",
            "Positve response": "are better at cooking",
            "Negative Response": "are worse at cooking",
            "Total": 231,
            "Yes": 99,
            "No": 132
        },
        {
            "Number": 43,
            "Question": "Do you change your bed sheets more",
            "Pro": "more",
            "Neg": "less",
            "Positve response": "change their bed sheets more",
            "Negative Response": "change their bed sheets less",
            "Total": 205,
            "Yes": 28,
            "No": 177
        },
        {
            "Number": 44,
            "Question": "Do you have more common sense",
            "Pro": "I have more",
            "Neg": "I have less",
            "Positve response": "have more common sense",
            "Negative Response": "have less common sense",
            "Total": 154,
            "Yes": 114,
            "No": 40
        },
        {
            "Number": 45,
            "Question": "Are more confident ",
            "Pro": "I'm more",
            "Neg": "I'm less",
            "Positve response": "are more confident",
            "Negative Response": "are less confident",
            "Total": 143,
            "Yes": 50,
            "No": 93
        }
    ]