let questions = [
    [
        1,
        "Do you walk faster",
        "I'm faster",
        "I'm slower",
        "walk faster",
        "walk slower",
        906,
        628,
        279
    ],
    [
        2,
        "Do you eat healthier food",
        "I'm healthier",
        "I'm less healthily",
        "eat healthier",
        "eat less healthily",
        906,
        367,
        539
    ],
    [
        3,
        "Do you care more about the environment",
        "I care more",
        "I care less",
        "care more about the enviroment",
        "care less about the enviroment",
        906,
        650,
        257
    ],
    [
        4,
        "Are you better at keeping your home tidy",
        "I'm better",
        "I'm worse",
        "are better at keeping their home tidy",
        "are worse at keeping their home tidy",
        906,
        247,
        660
    ],
    [
        5,
        "Are you smarter",
        "I'm smarter",
        "I'm less smart ",
        "are smarter",
        "are less smart",
        906,
        786,
        120
    ],
    [
        6,
        "Are your feet look better",
        "they're better",
        "they're worse",
        "have better looking feet",
        "have worse looking feet",
        906,
        317,
        590
    ],
    [
        7,
        "Are you a better listener",
        "I'm better",
        "I'm worse",
        "are a better listener",
        "are a worse listener",
        863,
        483,
        381
    ],
    [
        8,
        "Are you more privileged",
        "I'm more",
        "I'm less",
        "are more privileged",
        "are less privileged",
        906,
        748,
        158
    ],
    [
        9,
        "Do you smell better",
        "I smell better",
        "I smell worse",
        "smell better",
        "smell worse",
        906,
        410,
        496
    ],
    [
        10,
        "Are you a better communicator",
        "I'm better",
        "I'm worse",
        "are a better communicator",
        "are a worse communicator",
        870,
        382,
        488
    ],
    [
        11,
        "Are you better at washing up dishes",
        "I'm better",
        "I'm worse",
        "are better at washing up",
        "are worse at washing up",
        905,
        350,
        555
    ],
    [
        12,
        "Are you more curious",
        "I'm more",
        "I'm less",
        "are more curious",
        "are less curious",
        906,
        745,
        162
    ],
    [
        13,
        "Are you happier",
        "I'm happier",
        "I'm less happy",
        "are happier",
        "are less happy",
        906,
        350,
        556
    ],
    [
        14,
        "Are you kinder",
        "I'm kinder",
        "I'm less kind",
        "are kinder",
        "are less kind",
        906,
        651,
        255
    ],
    [
        15,
        "Do you have better ideas",
        "they're beter",
        "they're worse",
        "have better ideas",
        "have worse ideas",
        906,
        547,
        360
    ],
    [
        16,
        "Are you more conservative",
        "I'm more",
        "I'm less",
        "are more conservative",
        "are less conservative",
        906,
        125,
        781
    ],
    [
        17,
        "Do you complain more",
        "I complain more",
        "I complain less",
        "complain more",
        "complain less",
        906,
        453,
        454
    ],
    [
        18,
        "Do you give more to homeless  people",
        "I give more",
        "I give less",
        "give more to homeless people",
        "give less to homeless people",
        906,
        189,
        718
    ],
    [
        19,
        "Do you have a better music taste",
        "It's better",
        "It's worse",
        "have a better music taste",
        "have a worse music taste",
        906,
        542,
        364
    ],
    [
        20,
        "Do you give better gifts",
        "they're better",
        "they're worse",
        "give better gifts",
        "give worse gifts",
        906,
        324,
        583
    ],
    [
        21,
        "Are you a better friend",
        "I'm better",
        "I'm worse",
        "are a better friend",
        "are a worse friend",
        906,
        412,
        494
    ],
    [
        22,
        "Are you more progressive",
        "I'm more",
        "I'm less",
        "are more progressive",
        "are less progressive",
        906,
        733,
        174
    ],
    [
        23,
        "Are you better looking",
        "I'm better",
        "I'm worse",
        "are better looking",
        "are worse looking",
        906,
        375,
        532
    ],
    [
        24,
        "Are you more interesting",
        "I'm more",
        "I'm less",
        "are more interesting",
        "are less interesting",
        820,
        402,
        419
    ],
    [
        25,
        "Are you better at your work",
        "I'm better",
        "I'm worse",
        "are better at their work",
        "are worse at their work",
        818,
        472,
        346
    ],
    [
        26,
        "Are you more ambitious",
        "I'm more",
        "I'm less",
        "are more ambitious",
        "are less ambitious",
        814,
        331,
        483
    ],
    [
        27,
        "Are you more creative",
        "I'm more",
        "I'm less",
        "are more creative",
        "are less creative",
        772,
        403,
        369
    ],
    [
        28,
        "Are you better at sex",
        "I'm better",
        "I'm worse",
        "are beter at sex",
        "are worse at sex",
        244,
        78,
        166
    ],
    [
        29,
        "Are you more patient",
        "I'm more",
        "I'm less",
        "are more patient",
        "are less patient",
        772,
        451,
        321
    ],
    [
        30,
        "Do you have better dental hygiene",
        "better",
        "worse",
        "have better dental hygiene",
        "have worse dental hygiene",
        272,
        109,
        164
    ],
    [
        31,
        "Do you procrastinate more",
        "more",
        "less",
        "procrastinate more",
        "procrastinate less",
        272,
        232,
        40
    ],
    [
        32,
        "Are you a better driver",
        "I'm better",
        "I'm worse",
        "are a better driver",
        "are a worse driver",
        272,
        111,
        162
    ],
    [
        33,
        "Did you have a better childhood",
        "it was better",
        "it was worse",
        "had a better childhood",
        "had a worse childhood",
        271,
        185,
        87
    ],
    [
        34,
        "Are you a better hugger",
        "I'm better",
        "I'm worse",
        "are a better hugger",
        "are a worse hugger",
        269,
        123,
        146
    ],
    [
        35,
        "Are you funnier",
        "I'm funnier",
        "I'm less funny",
        "are funnier",
        "are less funny",
        269,
        157,
        112
    ],
    [
        36,
        "Are you better at maths",
        "I'm better",
        "I'm worse",
        "are better at maths",
        "are worse at maths",
        269,
        175,
        94
    ],
    [
        37,
        "Do you spend more time on your phone",
        "more",
        "less",
        "spend more time on their phone",
        "spend less time on their phone",
        267,
        165,
        103
    ],
    [
        38,
        "Are you more narcissitic",
        "I'm more",
        "I'm less",
        "are more narcissitic",
        "are less narcissitic",
        266,
        97,
        169
    ],
    [
        39,
        "Are you more sterotypically your gender",
        "I'm more",
        "I'm less",
        "are more sterotypically their gender",
        "are less sterotypically their gender",
        261,
        52,
        209
    ],
    [
        40,
        "Do you have a better memory",
        "it's better",
        "it's worse",
        "have a better memory",
        "have a worse memory",
        261,
        101,
        160
    ],
    [
        41,
        "Are you more humble",
        "I'm more",
        "I'm less",
        "are more humble",
        "are less humble",
        253,
        133,
        120
    ],
    [
        42,
        "Are you better at cooking",
        "I'm better",
        "I'm worse",
        "are better at cooking",
        "are worse at cooking",
        161,
        61,
        100
    ],
    [
        43,
        "Do you change your bed sheets more",
        "more",
        "less",
        "change their bed sheets more",
        "change their bed sheets less",
        148,
        22,
        126
    ],
    [
        44,
        "Do you have more common sense",
        "I have more",
        "I have less",
        "have more common sense",
        "have less common sense",
        122,
        84,
        38
    ],
    [
        45,
        "Are more confident ",
        "I'm more",
        "I'm less",
        "are more confident",
        "are less confident",
        117,
        38,
        79
    ],
    [
        46,
        "Do you exercise more",
        "more",
        "less",
        "exercise more",
        "exercise less",
        5,
        2,
        3
    ],
    [
        47,
        "Do you read more",
        "more",
        "less",
        "read more",
        "read less",
        5,
        1,
        4
    ],
    [
        48,
        "Do you sleep more",
        "more",
        "less",
        "sleep more",
        "sleep less",
        5,
        3,
        2
    ],
    [
        49,
        "Do you have more friends ",
        "I have more",
        "I have less",
        "have more friends",
        "have less friends",
        5,
        3,
        2
    ],
    [
        50,
        "Are you healthier",
        "I'm healthier",
        "I'm less healthy",
        "are healthier",
        "are less healthy",
        5,
        3,
        2
    ],
    [
        51,
        "Are you more religious",
        "I'm more",
        "I'm less",
        "are more religious",
        "are less religious",
        5,
        0,
        5
    ],
    [
        52,
        "Are you more optimistic",
        "I'm more",
        "I'm less",
        "are more optimistic",
        "are less optimistic",
        5,
        3,
        2
    ]
]
        
    

    